name: sgdn

dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - tensorflow
  - tensorboard
  - tensorboardX
  - ipykernel
  - matplotlib
  - scikit-learn
  - pandas
  - openpyxl
  - pip
  - tqdm
  - pip:
    - pickle5
    - wandb